# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-v2-auth-service
description: LFX Platform V2 Auth Service chart
type: application
version: 0.3.0
appVersion: "latest"
